DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE 

CREATE TABLE USERS (
    USER_ID    VARCHAR2(18 BYTE) PRIMARY KEY,
    PASSWORD   VARCHAR2(100 BYTE) NOT NULL,
    USERNAME   VARCHAR2(100 BYTE) NOT NULL,
    EMAIL      VARCHAR2(100 BYTE),
    PHONE      VARCHAR2(15 BYTE)
);

CREATE TABLE STUDYGROUP (
	GROUP_ID	CHAR(200 BYTE) PRIMARY KEY,
	GROUPNAME	VARCHAR2(200 BYTE) NOT NULL,
	GROUPDESCRIPTION	VARCHAR2(500 BYTE),
	GOAL		VARCHAR2(200 BYTE),
	CATEGORY	VARCHAR2(100 BYTE),
	MAXMEMBER	NUMBER(10 BYTE)
);

COMMIT;

