DROP TABLE USERS CASCADE CONSTRAINTS;

CREATE TABLE USERS (
    USER_ID    VARCHAR2(18 BYTE) PRIMARY KEY,
    PASSWORD   VARCHAR2(100 BYTE) NOT NULL,
    USERNAME   VARCHAR2(100 BYTE) NOT NULL,
    EMAIL      VARCHAR2(100 BYTE),
    PHONE      VARCHAR2(15 BYTE)
);

COMMIT;

